### ISSUE TITLE
64 bit from container

### ISSUE THREAD

**Issue by sameersheorey** [GregDMeyer/dynamite#15]
Hi Greg,

Thanks for creating dynamite!

I would like to use dynamite for some research I am doing on SYK type models. I am looking to calculate spectra for Hamiltonians with number of fermions N>30. I am having difficulty installing from source onto our cluster so have been using singularity to run from container. When running my code N=40 for example I get the error:

5280628736 is too big for PetscInt, you may need to ./configure using --with-64-bit-indices. 

Is it possible to run with 64 bit from a container or would I need to work out how to install from source?

Thanks
Sam

**Comment by GregDMeyer** [comment]
Hi Sam!

This is no problem, I just should add 64 bit builds to the docker workflow. I'll do that when I have a moment (hopefully in the next day or two) and let you know!

Cheers,
Greg

P.S. N=40 is really pushing it, but that's awesome if you get it to run! You will definitely need to set `config.shell = True`, particularly for an SYK model that presumably has a lot of terms in the Hamiltonian, otherwise the matrix with consume an intractable amount of memory to store.

**Comment by GregDMeyer** [comment]
OK, I just pushed 64-bit builds to docker hub! Give it a try using the the "latest-int64" image and let me know if you have any issues!
