### ISSUE TITLE
Readthedocs main page shows the wrong docker command

### ISSUE THREAD

**Issue by erinaldi** [GregDMeyer/dynamite#31]
Hello,

I would like to make sure that I am not doing anything wrong when running the tutorials in the docker container image of `dynamite`.

The main page https://dynamite.readthedocs.io/en/latest/ of the `dynamite` documentations shows a docker command:
```
docker run --rm -p 8887:8887 -w /home/dnm/examples/tutorial gdmeyer/dynamite:latest
```
which does not work as expected.
In fact it does not have `jupyter` installed and I suspect the command should be changed to
```
docker run --rm -p 8887:8887 -w /home/dnm/examples/tutorial gdmeyer/dynamite:latest-jupyter
```

I also have a related question about running a MPI jobs with dynamite using the docker container but without `singularity` or `shifter`. Is that actually possible?

**Comment by GregDMeyer** [comment]
Fixed by [ad6ec95](https://github.com/GregDMeyer/dynamite/commit/ad6ec957b49647596aa263cafdbd4b3a9ffdf001). Thanks for the heads up, that was an embarrassing mistake!

> I also have a related question about running a MPI jobs with dynamite using the docker container but without `singularity` or `shifter`. Is that actually possible?

You should be able to do so simply by executing `mpirun` inside of the container. See the second "note" in the quick usage guide for containers [here](https://dynamite.readthedocs.io/en/latest/containers.html#quick-usage-guide).
